# Generated by Django 4.2.11 on 2024-03-09 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.istockphoto.com%2Fphotos%2Fcoming-soon-food&psig=AOvVaw1TW3dCBZ0gKOlnMtlY-9DP&ust=1710057249950000&source=images&cd=vfe&opi=89978449&ved=0CBMQjRxqFwoTCJjThenZ5oQDFQAAAAAdAAAAABAE', max_length=500),
        ),
    ]
