# Generated by Django 4.2.11 on 2024-03-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodApp', '0002_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.everestkitchenpa.com%2Fassets%2Fpages%2FfriedRice.html&psig=AOvVaw1TW3dCBZ0gKOlnMtlY-9DP&ust=1710057249950000&source=images&cd=vfe&opi=89978449&ved=0CBMQjRxqFwoTCJjThenZ5oQDFQAAAAAdAAAAABAO', max_length=500),
        ),
    ]
