# Generated by Django 4.2.11 on 2024-03-23 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodApp', '0004_item_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://media.istockphoto.com/id/1137255480/vector/coming-soon-sign.jpg?s=1024x1024&w=is&k=20&c=6ey80gBK_vWoOHJSNzeNL1KXVCGHevn1bXTsafUF0U4=', max_length=500),
        ),
    ]
